# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Averil Prost'
tagline:          Personal webpage
description:      PhD student in maths.
url:              https://averil-prost.github.io
baseurl:          /
github_username: averil-prost

author:
  name:           'Averil Prost'
  url:            https://github.com/averil-prost
  email:	  averil.prost@inda-rouen.fr

github:
  repo:           https://github.com/averil-prost/averil-prost.github.io
  
plugins:
  - jekyll-feed
  
